import QtQuick
import Quickshell
import Quickshell.Io
import qs.Commons
import qs.Services.UI

Item {
    id: root
    property var pluginApi: null

    readonly property string configBase: Quickshell.env("XDG_CONFIG_HOME") || (Quickshell.env("HOME") + "/.config")
    readonly property string configDir: configBase + "/niri"
    readonly property string mainConfig: configDir + "/config.kdl"
    readonly property string layoutConfig: configDir + "/layout.kdl"

    Component.onCompleted: {
        Logger.i("NiriLayout", "Plugin Loaded! Starting setup process...")
        setupProcess.running = true
    }

    Process {
        id: setupProcess
        command: ["bash", "-c", root.installScript]

        stdout: SplitParser {
            onRead: (data) => {
                Logger.d("NiriLayout", "Script Output: " + data)
                if (data.trim() === "CHANGED") {
                    reloadProcess.running = true
                    ToastService.showNotice(qsTr("Plugin installed & Layout injected."))
                }
            }
        }
    }

    readonly property string installScript: `
        DIR="${root.configDir}"
        MAIN="${root.mainConfig}"
        LAYOUT="${root.layoutConfig}"
        
        mkdir -p "$DIR"

        if [ ! -f "$LAYOUT" ]; then
            echo '// Auto-generated by Plugin' > "$LAYOUT"
            echo 'layout { center-focused-column "always"; }' >> "$LAYOUT"
        fi

        if ! grep -q 'include "layout.kdl"' "$MAIN"; then
            # Backup
            cp "$MAIN" "$MAIN.bak"
            
            # Append include
            echo '' >> "$MAIN"
            echo '// Auto-added by Niri Layout Switcher Plugin' >> "$MAIN"
            echo 'include "layout.kdl"' >> "$MAIN"
            
            echo "CHANGED"
        fi
    `
    
    Process {
        id: reloadProcess
        command: ["niri", "msg", "action", "reload-config-file"]
    }

    Process { id: layoutProcess }

    IpcHandler {
        target: "plugin:niri-layout-mode"

        function setMode(modeName) {
            Logger.i("NiriLayout", "setMode called with: " + modeName)
            if (!pluginApi) return

            var targetMode = modeName.toLowerCase()
            var centerVal = "always" // Default Center
            var label = "Center Mode"

            if (targetMode === "split") {
                centerVal = "never"
                label = "Split Mode"
            } 

            var fileContent = `// Auto-generated by Niri Layout Switcher
layout {
    center-focused-column "${centerVal}"
}`
            
            var cmd = `printf '${fileContent}' > "${root.layoutConfig}" && niri msg action reload-config-file`

            layoutProcess.command = ["bash", "-c", cmd]
            layoutProcess.running = true

            // Update UI & Settings
            pluginApi.pluginSettings.mode = targetMode
            pluginApi.saveSettings()
            
            ToastService.showNotice("Layout: " + label)
        }
        
        function toggle() {
            Logger.d("NiriLayout", "Toggle clicked!")
             var current = pluginApi.pluginSettings.mode || "center"
             setMode(current === "center" ? "split" : "center")
        }
    }
}