import QtQuick
import Quickshell
import Quickshell.Io
import qs.Commons
import qs.Services.UI

Item {
    id: root
    property var pluginApi: null

    property string internalMode: "center"

    readonly property string configBase: Quickshell.env("XDG_CONFIG_HOME") || (Quickshell.env("HOME") + "/.config")
    readonly property string configDir: configBase + "/niri"
    readonly property string mainConfig: configDir + "/config.kdl"
    readonly property string layoutConfig: configDir + "/layout.kdl"

    function setMode(modeName) {
        if (!pluginApi) return 

        var targetMode = modeName.toLowerCase()
        var centerVal = "always"
        var label = "Center Mode"

        if (targetMode === "split") {
            centerVal = "never"
            label = "Split Mode"
        } 

        // Tulis file
        var fileContent = `// Auto-generated by Niri Layout Switcher
layout {
    center-focused-column "${centerVal}"
}`
        
        var cmd = `printf '${fileContent}' > "${root.layoutConfig}" && niri msg action reload-config-file`

        layoutProcess.command = ["bash", "-c", cmd]
        layoutProcess.running = true

        pluginApi.pluginSettings.mode = targetMode
        pluginApi.saveSettings()
        
        ToastService.showNotice("Layout: " + label)
    }

    Component.onCompleted: {
        Logger.i("NiriLayout", "Plugin Loaded! Starting setup process...")
        setupProcess.running = true
        if (pluginApi && pluginApi.pluginSettings.mode) {
             root.internalMode = pluginApi.pluginSettings.mode
        }
    }

    Process {
        id: setupProcess
        command: ["bash", "-c", root.installScript]

        stdout: SplitParser {
            onRead: (data) => {
                Logger.d("NiriLayout", "Script Output: " + data)
                if (data.trim() === "CHANGED") {
                    reloadProcess.running = true
                    ToastService.showNotice(qsTr("Plugin installed & Layout injected."))
                }
            }
        }
    }

    readonly property string installScript: `
        DIR="${root.configDir}"
        MAIN="${root.mainConfig}"
        LAYOUT="${root.layoutConfig}"
        
        mkdir -p "$DIR"

        if [ ! -f "$LAYOUT" ]; then
            echo '// Auto-generated by Plugin' > "$LAYOUT"
            echo 'layout { center-focused-column "always"; }' >> "$LAYOUT"
        fi

        if ! grep -q 'include "layout.kdl"' "$MAIN"; then
            # Backup
            cp "$MAIN" "$MAIN.bak"
            
            # Append include
            echo '' >> "$MAIN"
            echo '// Auto-added by Niri Layout Switcher Plugin' >> "$MAIN"
            echo 'include "layout.kdl"' >> "$MAIN"
            
            echo "CHANGED"
        fi
    `
    
    Process {
        id: reloadProcess
        command: ["niri", "msg", "action", "reload-config-file"]
    }

    Process { id: layoutProcess }

    IpcHandler {
        target: "plugin:niri-layout-mode"

        function getMode() {
            if (!pluginApi) return "center"
            return pluginApi.pluginSettings.mode || "center"
        }
        
        function toggle() {
             var current = pluginApi ? (pluginApi.pluginSettings.mode || "center") : "center"
             var nextMode = (current === "center" ? "split" : "center")
             
             root.setMode(nextMode)
             
             return nextMode
        }
    }
}